language: haskell
before_install:
  - cabal update
  - git clone --quiet -b lens git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - cd diagrams
  - cabal install diagrams-core/
  - cd ..
script:
  - cabal configure --enable-tests && cabal build --ghc-options='-Wall -Werror' && cabal test && cabal haddock
notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-lib\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
